# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: S.T.A. Servizi Tecnici Avanzati s.r.l.
piva: 03079520809
pec: sta@pecditta.com
email: sta.srl@outlook.it
description: >-
  Offriamo servizi di recupero e rilancio di realtà industriali non più produttive, consulenze e progettazione di natura tecnico-informatica e mediazione nella compravendita di beni derivanti da liquidazioni e fallimenti.
  Massima serietà e correttezza sono il nostro secondo nome, cerchiamo di venire incontro accontentando le esigenze dei nostri clienti.
baseurl: ""
url: "https://sos.sm"

# Build settings

markdown: kramdown

theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

#theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      show_sidebar: false

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
